# UTS

## 1. Jelaskan konsep kemiripan pada pembelajaran mesin, berikan contoh kasus nyata!

Dalam pembelajaran mesin, konsep **kemiripan** adalah dasar perhitungan untuk menentukan seberapa dekat hubungan antara dua objek atau data poin berdasarkan fitur-fitur yang dimilikinya. Algoritma mengukur **kemiripan** ini menggunakan fungsi jarak (seperti *Euclidean distance*). Prinsip utamanya adalah data yang memiliki nilai jarak yang kecil satu sama lain dianggap memiliki **kemiripan** yang tinggi dan cenderung memiliki label atau perilaku yang sama. Konsep ini menjadi fondasi bagi algoritma seperti *K-Nearest Neighbors* (KNN), *K-Means Clustering*, dan sistem rekomendasi.

Salah satu contoh penerapan konsep **kemiripan** adalah pada **Sistem Rekomendasi Film (seperti Netflix atau Disney+)**.
* **Skenario:** Sistem akan menghitung **kemiripan** antara profil Anda dengan profil pengguna lain.
* **Penerapan:** Jika Anda menyukai film *genre* aksi dan *sci-fi*, sistem akan mencari pengguna lain yang memiliki pola tontonan dengan **kemiripan** tinggi dengan Anda (juga menyukai aksi dan *sci-fi*).
* **Hasil:** Jika pengguna yang memiliki **kemiripan** tersebut menyukai sebuah film baru yang belum Anda tonton, sistem akan merekomendasikan film tersebut kepada Anda karena asumsi bahwa preferensi kalian memiliki **kemiripan**.

## 2. Lakukan normalisasi Min-Max pada data di tabel berikut:

| Karyawan | Gaji (IDR) | Umur (Tahun) |
| --- | --- | --- |
| A | 5.000.000 | 25 |
| B | 8.000.000 | 40 |
| C | 6.500.000 | 30 |
| D | 10.000.000 | 50 |
| E | 4.000.000 | 22 |

In [100]:
import pandas as pd
from IPython.display import display
from sklearn.preprocessing import MinMaxScaler

In [101]:
data = {
    'Karyawan': ['A', 'B', 'C', 'D', 'E'],
    'Gaji': [5000000, 8000000, 6500000, 10000000, 4000000],
    'Umur': [25, 40, 30, 50, 22]
}

df = pd.DataFrame(data)
display(df)

  Karyawan      Gaji  Umur
0        A   5000000    25
1        B   8000000    40
2        C   6500000    30
3        D  10000000    50
4        E   4000000    22

In [102]:
scaler = MinMaxScaler()
df_normalized = df.copy()
df_normalized[['Gaji', 'Umur']] = scaler.fit_transform(df[['Gaji', 'Umur']])

In [103]:
print("--- Data Setelah Normalisasi Min-Max (0-1) ---")
display(df_normalized.round(4))

--- Data Setelah Normalisasi Min-Max (0-1) ---

  Karyawan    Gaji    Umur
0        A  0.1667  0.1071
1        B  0.6667  0.6429
2        C  0.4167  0.2857
3        D  1.0000  1.0000
4        E  0.0000  0.0000

## 3. Titik yang akan diklasifikasikan: $ X=(38,75) $ , gunakan KNN dengan $ K=3 $

| ID | Fitur () | Fitur () | Label |
| --- | --- | --- | --- |
| 1 | 35 | 71 | Beli |
| 2 | 43 | 63 | Tidak Beli |
| 3 | 31 | 75 | Beli |
| 4 | 30 | 69 | Tidak Beli |
| 5 | 44 | 83 | Beli |
| 16 | 38 | 67 | Tidak Beli |

In [104]:
import pandas as pd, numpy as np

from IPython.display import display
from collections import Counter

In [105]:
# 1. Menyiapkan Dataset
data = {
    'ID': [1, 2, 3, 4, 5, 16],
    'x1': [35, 43, 31, 30, 44, 38],
    'x2': [71, 63, 75, 69, 83, 67],
    'Label': ['Beli', 'Tidak Beli', 'Beli', 'Tidak Beli', 'Beli', 'Tidak Beli']
}

df = pd.DataFrame(data)
display(df)

   ID  x1  x2       Label
0   1  35  71        Beli
1   2  43  63  Tidak Beli
2   3  31  75        Beli
3   4  30  69  Tidak Beli
4   5  44  83        Beli
5  16  38  67  Tidak Beli

In [106]:
# Titik yang akan diklasifikasikan
X_baru = np.array([38, 75])
K = 3

In [107]:
def euclidean_distance(point1, point2):
    return np.sqrt(np.sum((point1 - point2)**2))

Jarak Euclidean antara dua titik $ \mathbf{p} = (p_1, p_2, \dots, p_n) $ dan $ \mathbf{q} = (q_1, q_2, \dots, q_n) $ dalam ruang berdimensi-$n$ diberikan oleh:

$$
d(\mathbf{p}, \mathbf{q}) = \sqrt{\sum_{i=1}^{n} (p_i - q_i)^2}
$$

Atau dalam bentuk lebih eksplisit:

$$
d(\mathbf{p}, \mathbf{q}) = \sqrt{(p_1 - q_1)^2 + (p_2 - q_2)^2 + \cdots + (p_n - q_n)^2}
$$

In [108]:
distances = []

# Hitung jarak dari X_baru ke setiap titik di dataset
for index, row in df.iterrows():
    current_point = np.array([row['x1'], row['x2']])
    dist = euclidean_distance(X_baru, current_point)
    distances.append((dist, row['Label']))

# Urutkan berdasarkan jarak terdekat (ascending)
distances.sort(key=lambda x: x[0])

# Ambil K tetangga terdekat
k_nearest_neighbors = distances[:K]

# Voting Mayoritas
k_labels = [label for dist, label in k_nearest_neighbors]
vote_result = Counter(k_labels).most_common(1)[0][0]

In [109]:
print(f"Data Training:\n{df}")

Data Training:
   ID  x1  x2       Label
0   1  35  71        Beli
1   2  43  63  Tidak Beli
2   3  31  75        Beli
3   4  30  69  Tidak Beli
4   5  44  83        Beli
5  16  38  67  Tidak Beli

In [110]:
print(f"Titik Baru: {X_baru}")

Titik Baru: [38 75]

In [111]:
print(f"Jarak ke Tetangga Terdekat (Top {K}):")
for i, (dist, label) in enumerate(k_nearest_neighbors):
    print(f"{i+1}. Jarak: {dist:.2f}, Label: {label}")

Jarak ke Tetangga Terdekat (Top 3):
1. Jarak: 5.00, Label: Beli
2. Jarak: 7.00, Label: Beli
3. Jarak: 8.00, Label: Tidak Beli

In [112]:
print(f"Hasil Klasifikasi dengan K={K}: {vote_result}")

Hasil Klasifikasi dengan K=3: Beli

## 4. Hitung “Nilai Kesehatan” Gita menggunakan KNN, dengan $ K=2 $

| ID | Nama | Umur | Pendapatan (USD) | Status Pernikahan | Nilai Kesehatan |
| --- | --- | --- | --- | --- | --- |
| 1 | Ali | 25 | 50000 | Menikah | 8 |
| 2 | Budi | 30 | NULL | Lajang | 7 |
| 3 | Citra | 22 | 45000 | Menikah | 9 |
| 4 | Dedi | 35 | 60000 | NULL | 6 |
| 5 | Evi | 28 | 52000 | Lajang | 5 |
| 6 | Fani | 40 | 70000 | Menikah | 10 |
| 7 | Gita | 29 | 48000 | Lajang | **?** |
| 8 | Hadi | 31 | 55000 | Menikah | 8 |

Dalam penyelesaian ini, kita perlu melakukan beberapa langkah *preprocessing* sebelum menerapkan KNN:

1. **Cleaning:** Data Gita yang akan diprediksi memiliki umur "29.". Kita akan anggap 29.
2. **Handling Missing Values:** Data latih (Budi dan Dedi) memiliki nilai fitur yang kosong (`NULL`) pada Pendapatan dan Status. Dalam KNN standar, kita tidak bisa menghitung jarak jika ada data kosong. Solusi paling aman dan sederhana adalah **menghapus baris data latih yang tidak lengkap** agar perhitungan jarak valid.
3. **Encoding:** Mengubah "Status Pernikahan" menjadi angka (Misal: Lajang = 0, Menikah = 1).
4. **Normalisasi:** Menggunakan Min-Max Scaling agar fitur dengan angka besar (Pendapatan) tidak mendominasi perhitungan jarak dibandingkan fitur angka kecil (Umur).
5. **Prediksi:** Menggunakan rata-rata dari 2 tetangga terdekat (K=2) karena targetnya adalah "Nilai" (Regresi).

In [113]:
import pandas as pd, numpy as np

from IPython.display import display
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import MinMaxScaler

In [114]:
data = {
    'Nama': ['Ali', 'Budi', 'Citra', 'Dedi', 'Evi', 'Fani', 'Gita', 'Hadi'],
    'Umur': [25, 30, 22, 35, 28, 40, 29, 31],
    'Pendapatan': [50000, np.nan, 45000, 60000, 52000, 70000, 48000, 55000],
    'Status_Pernikahan': ['Menikah', 'Lajang', 'Menikah', np.nan, 'Lajang', 'Menikah', 'Lajang', 'Menikah'],
    'Nilai_Kesehatan': [8, 7, 9, 6, 5, 10, np.nan, 8]
}

df = pd.DataFrame(data)
display(df)

    Nama  Umur  Pendapatan Status_Pernikahan  Nilai_Kesehatan
0    Ali    25     50000.0           Menikah              8.0
1   Budi    30         NaN            Lajang              7.0
2  Citra    22     45000.0           Menikah              9.0
3   Dedi    35     60000.0               NaN              6.0
4    Evi    28     52000.0            Lajang              5.0
5   Fani    40     70000.0           Menikah             10.0
6   Gita    29     48000.0            Lajang              NaN
7   Hadi    31     55000.0           Menikah              8.0

In [115]:
# Encoding Status Pernikahan: Lajang=0, Menikah=1
status_map = {'Lajang': 0, 'Menikah': 1}
df['Status_Encoded'] = df['Status_Pernikahan'].map(status_map)

# Pisahkan Data Gita (yang mau diprediksi) dan Data Training
gita_data = df[df['Nama'] == 'Gita'].copy()
train_data = df[df['Nama'] != 'Gita'].copy()

# Bersihkan Data Training: Hapus baris yang punya nilai NaN di fitur (Pendapatan atau Status)
# Budi (NaN Pendapatan) dan Dedi (NaN Status) akan dihapus dari training set
train_clean = train_data.dropna(subset=['Pendapatan', 'Status_Encoded'])

# Fitur yang dipakai: Umur, Pendapatan, Status
features = ['Umur', 'Pendapatan', 'Status_Encoded']
X_train = train_clean[features]
y_train = train_clean['Nilai_Kesehatan']
X_test = gita_data[features]

In [116]:
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [117]:
# Menggunakan Regresi karena outputnya adalah nilai skor (kontinu/ordinal)
K = 2
knn = KNeighborsRegressor(n_neighbors=K)
knn.fit(X_train_scaled, y_train)

# Prediksi
prediction = knn.predict(X_test_scaled)

# Mencari Tetangga Terdekat (untuk informasi tambahan)
distances, indices = knn.kneighbors(X_test_scaled)
neighbors = train_clean.iloc[indices[0]]

In [118]:
print("Data Training Bersih (Tanpa Budi & Dedi):")
display(train_clean[['Nama', 'Umur', 'Pendapatan', 'Status_Pernikahan', 'Nilai_Kesehatan']])

Data Training Bersih (Tanpa Budi & Dedi):

    Nama  Umur  Pendapatan Status_Pernikahan  Nilai_Kesehatan
0    Ali    25     50000.0           Menikah              8.0
2  Citra    22     45000.0           Menikah              9.0
4    Evi    28     52000.0            Lajang              5.0
5   Fani    40     70000.0           Menikah             10.0
7   Hadi    31     55000.0           Menikah              8.0

In [119]:
print("Data Gita:")
display(gita_data[['Nama', 'Umur', 'Pendapatan', 'Status_Pernikahan']])

Data Gita:

   Nama  Umur  Pendapatan Status_Pernikahan
6  Gita    29     48000.0            Lajang

In [120]:
print(f"2 Tetangga Terdekat dengan Gita:")
for i, idx in enumerate(indices[0]):
    nama_tetangga = train_clean.iloc[idx]['Nama']
    dist = distances[0][i]
    val = y_train.iloc[idx]
    print(f"- {nama_tetangga} (Jarak: {dist:.4f}, Nilai Kesehatan: {val})")

2 Tetangga Terdekat dengan Gita:
- Evi (Jarak: 0.1694, Nilai Kesehatan: 5.0)
- Ali (Jarak: 1.0275, Nilai Kesehatan: 8.0)

In [121]:
print(f"Prediksi Nilai Kesehatan Gita (Rata-rata K=2): {prediction[0]:.2f}")

Prediksi Nilai Kesehatan Gita (Rata-rata K=2): 6.50