In [12]:
import pandas as pd
df1= pd.read_csv('../data/csv/all-task-3-detailed-reviews.csv')
df2 = pd.read_csv('../data/csv/all-task-3-featured-reviews.csv')
df3 = pd.read_csv('../data/csv/all-task-3-overview.csv')
df4 = pd.read_csv('../data/csv/all-task-3.csv')

In [13]:
df1.head()

,place_id,place_name,review_id,review_link,name,reviewer_id,reviewer_profile,rating,review_text,published_at,...,response_from_owner_text,response_from_owner_ago,response_from_owner_date,total_number_of_reviews_by_reviewer,total_number_of_photos_by_reviewer,is_local_guide,review_translated_text,response_from_owner_translated_text,experience_details,review_photos
0,ChIJYQIbq0US2C0RoXbX5gkHWUY,Kahoona Beach,Ci9DQUlRQUNvZENodHljRjlvT2paRWVubEVTSE5aTFZaVV...,https://www.google.com/maps/reviews/data=!4m8!...,abdul kholik,107620629851447557931,https://www.google.com/maps/contrib/1076206298...,5,Sperti apa ya sekarang akses masuknya?,a week ago,...,NaN,NaN,NaN,88,56,1.0,What is the access like now?,NaN,[],[]
1,ChIJYQIbq0US2C0RoXbX5gkHWUY,Kahoona Beach,ChdDSUhNMG9nS0VJQ0FnTUNZc05iSWpRRRAB,https://www.google.com/maps/reviews/data=!4m8!...,Nashra kamilah. Amel,115484787531730881553,https://www.google.com/maps/contrib/1154847875...,1,NaN,5 months ago,...,NaN,NaN,NaN,0,0,NaN,NaN,NaN,[],[]
2,ChIJYQIbq0US2C0RoXbX5gkHWUY,Kahoona Beach,ChZDSUhNMG9nS0VJQ0FnSURUMjgyN0p3EAE,https://www.google.com/maps/reviews/data=!4m8!...,Supriyanto,107038615744599578222,https://www.google.com/maps/contrib/1070386157...,5,NaN,a year ago,...,NaN,NaN,NaN,164,4015,1.0,NaN,NaN,[],[]
3,ChIJYQIbq0US2C0RoXbX5gkHWUY,Kahoona Beach,ChdDSUhNMG9nS0VJQ0FnSUMxNGFtV3NnRRAB,https://www.google.com/maps/reviews/data=!4m8!...,Moh Ainul Yakin,107159143887900698122,https://www.google.com/maps/contrib/1071591438...,5,Pantai yg indah dengan sunsetnya,a year ago,...,NaN,NaN,NaN,1,3,NaN,Beautiful beach with sunset,NaN,[],[]
4,ChIJYQIbq0US2C0RoXbX5gkHWUY,Kahoona Beach,ChdDSUhNMG9nS0VJQ0FnSUQ2a09DNGdnRRAB,https://www.google.com/maps/reviews/data=!4m8!...,KEONG PUTRA KARANG,111359002941661778714,https://www.google.com/maps/contrib/1113590029...,5,Tempat bagus untuk cari ikan baik ngobor atau...,Edited 2 years ago,...,NaN,NaN,NaN,11,16,1.0,"A good place to look for fish, either by fishi...",NaN,[],"[{""id"":""CIHM0ogKEICAgIDp0p_-tgE"",""url"":""https:..."

In [14]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6622 entries, 0 to 6621
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   place_id                             6622 non-null   object
 1   place_name                           6622 non-null   object
 2   review_id                            6622 non-null   object
 3   review_link                          6622 non-null   object
 4   name                                 6622 non-null   object
 5   reviewer_id                          6622 non-null   object
 6   reviewer_profile                     6622 non-null   object
 7   rating                               6622 non-null   int64
 8   review_text                          3455 non-null   object
 9   published_at                         6622 non-null   object
 10  published_at_date                    6622 non-null   object
 11  response_from_owner_text             37 non-null     object
 12  response_from_owner_ago              39 non-null     object
 13  response_from_owner_date             39 non-null     object
 14  total_number_of_reviews_by_reviewer  6622 non-null   int64
 15  total_number_of_photos_by_reviewer   6622 non-null   int64
 16  is_local_guide                       3908 non-null   float64
 17  review_translated_text               3181 non-null   object
 18  response_from_owner_translated_text  33 non-null     object
 19  experience_details                   6622 non-null   object
 20  review_photos                        6622 non-null   object
dtypes: float64(1), int64(3), object(17)
memory usage: 1.1+ MB

In [15]:
df2.head()

,place_id,place_name,review_id,review_link,name,reviewer_id,reviewer_profile,rating,review_text,published_at,...,response_from_owner_text,response_from_owner_ago,response_from_owner_date,total_number_of_reviews_by_reviewer,total_number_of_photos_by_reviewer,is_local_guide,review_translated_text,response_from_owner_translated_text,experience_details,review_photos
0,ChIJYQIbq0US2C0RoXbX5gkHWUY,Kahoona Beach,ChdDSUhNMG9nS0VJQ0FnSUQ2a09DNGdnRRAB,https://www.google.com/maps/reviews/data=!4m8!...,KEONG PUTRA KARANG,111359002941661778714,https://www.google.com/maps/contrib/1113590029...,5,Tempat bagus untuk cari ikan baik ngobor atau...,Diedit 2 tahun lalu,...,NaN,NaN,NaN,11,16,1.0,NaN,NaN,[],"[{""id"":""CIHM0ogKEICAgIDp0p_-tgE"",""url"":""https:..."
1,ChIJYQIbq0US2C0RoXbX5gkHWUY,Kahoona Beach,Ci9DQUlRQUNvZENodHljRjlvT2paRWVubEVTSE5aTFZaVV...,https://www.google.com/maps/reviews/data=!4m8!...,abdul kholik,107620629851447557931,https://www.google.com/maps/contrib/1076206298...,5,Sperti apa ya sekarang akses masuknya?,seminggu lalu,...,NaN,NaN,NaN,88,56,1.0,NaN,NaN,[],[]
2,ChIJYQIbq0US2C0RoXbX5gkHWUY,Kahoona Beach,ChZDSUhNMG9nS0VJQ0FnSUNlejZ2NFN3EAE,https://www.google.com/maps/reviews/data=!4m8!...,Dora The explorer (ingin menjelajahi dunia),113438849045159051795,https://www.google.com/maps/contrib/1134388490...,5,tempat wisata gratis,3 tahun lalu,...,NaN,NaN,NaN,76,226,1.0,NaN,NaN,[],"[{""id"":""CIHM0ogKEICAgICez6v4qwE"",""url"":""https:..."
3,ChIJYQIbq0US2C0RoXbX5gkHWUY,Kahoona Beach,ChZDSUhNMG9nS0VJQ0FnSUNCN01mWkhBEAE,https://www.google.com/maps/reviews/data=!4m8!...,Emil Jarkovic,103530390808733518984,https://www.google.com/maps/contrib/1035303908...,4,"Pasir pantai putih yg bagus,gk kalah ama yg la...",2 tahun lalu,...,NaN,NaN,NaN,26,49,1.0,NaN,NaN,[],[]
4,ChIJYQIbq0US2C0RoXbX5gkHWUY,Kahoona Beach,ChdDSUhNMG9nS0VJQ0FnSURSdnVyVzNnRRAB,https://www.google.com/maps/reviews/data=!4m8!...,Muhammad Rosin,114064766086579499263,https://www.google.com/maps/contrib/1140647660...,1,Untuk Akses Nyampek Kepantainya Bisa Di Lewati...,2 tahun lalu,...,NaN,NaN,NaN,2,0,NaN,NaN,NaN,[],[]

In [16]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 512 entries, 0 to 511
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   place_id                             512 non-null    object
 1   place_name                           512 non-null    object
 2   review_id                            512 non-null    object
 3   review_link                          512 non-null    object
 4   name                                 512 non-null    object
 5   reviewer_id                          512 non-null    object
 6   reviewer_profile                     512 non-null    object
 7   rating                               512 non-null    int64
 8   review_text                          471 non-null    object
 9   published_at                         512 non-null    object
 10  published_at_date                    512 non-null    object
 11  response_from_owner_text             10 non-null     object
 12  response_from_owner_ago              10 non-null     object
 13  response_from_owner_date             10 non-null     object
 14  total_number_of_reviews_by_reviewer  512 non-null    int64
 15  total_number_of_photos_by_reviewer   512 non-null    int64
 16  is_local_guide                       370 non-null    float64
 17  review_translated_text               10 non-null     object
 18  response_from_owner_translated_text  1 non-null      object
 19  experience_details                   512 non-null    object
 20  review_photos                        512 non-null    object
dtypes: float64(1), int64(3), object(17)
memory usage: 84.1+ KB

In [17]:
df3.head()

,place_id,name,description,is_spending_on_ads,reviews,rating,competitors,website,phone,can_claim,...,featured_image,main_category,categories,workday_timing,is_temporarily_closed,closed_on,address,review_keywords,link,query
0,ChIJYQIbq0US2C0RoXbX5gkHWUY,Kahoona Beach,NaN,NaN,22,4.3,NaN,NaN,0857-3335-9123,NaN,...,https://lh3.googleusercontent.com/gps-cs-s/AC9...,Pantai,Pantai,NaN,NaN,Open All Days,"Beng Sobung, Tobaddung, Kec. Klampis, Kabupate...",wisata,https://www.google.com/maps/place/Kahoona+Beac...,beaches in bangkalan
1,ChIJxWCJ0M4C2C0RVkIRQqMGJHs,Pantai Goa Petapa,NaN,NaN,319,4.2,NaN,NaN,NaN,NaN,...,https://lh3.googleusercontent.com/gps-cs-s/AC9...,Pantai,Pantai,NaN,NaN,Open All Days,"Madura Island, East Java, Kejawan, Sukolilo Ti...","motor, wisata, pemandangan, sore, harga, tiket...",https://www.google.com/maps/place/Pantai+Goa+P...,beaches in bangkalan
2,ChIJCb-H_gM_2C0RotQ5H2cQ_9g,Pantai Siring Kemuning,NaN,NaN,511,4.0,NaN,http://www.pulaumadura.com/,NaN,NaN,...,https://lh3.googleusercontent.com/gps-cs-s/AC9...,Pantai,Pantai,NaN,NaN,Open All Days,"Macajah, Kec. Tj. Bumi, Kabupaten Bangkalan, J...","wisata, fasilitas, orang, tiket, motor, kebers...",https://www.google.com/maps/place/Pantai+Sirin...,beaches in bangkalan
3,ChIJF_T0zSUD2C0RJFytakQa2VM,Pantai Rindu,NaN,NaN,1386,3.7,Name: Dermaga Rindu\nLink: https://www.google....,NaN,NaN,1.0,...,https://lh3.googleusercontent.com/gps-cs-s/AC9...,Tujuan Wisata,Tujuan Wisata,NaN,NaN,Open All Days,NaN,"foto, menu, cafe, pemandangan, pesan, makanan ...",https://www.google.com/maps/place/Pantai+Rindu...,beaches in bangkalan
4,ChIJuRiSbwAd2C0RDp_Iezqhlmk,Merah Putih Beach,NaN,NaN,1,5.0,Name: Pantai Gebang\nLink: https://www.google....,NaN,NaN,1.0,...,https://lh3.googleusercontent.com/gps-cs-s/AC9...,Tujuan Wisata,Tujuan Wisata,NaN,NaN,Open All Days,"RRR8+4R, Karang Pandan, Sukolilo Tim., Kec. La...",NaN,https://www.google.com/maps/place/Merah+Putih+...,beaches in bangkalan

In [18]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   place_id               96 non-null     object
 1   name                   96 non-null     object
 2   description            13 non-null     object
 3   is_spending_on_ads     0 non-null      float64
 4   reviews                96 non-null     int64
 5   rating                 96 non-null     float64
 6   competitors            68 non-null     object
 7   website                11 non-null     object
 8   phone                  18 non-null     object
 9   can_claim              52 non-null     float64
 10  owner_name             68 non-null     object
 11  owner_profile_link     13 non-null     object
 12  featured_image         92 non-null     object
 13  main_category          96 non-null     object
 14  categories             96 non-null     object
 15  workday_timing         45 non-null     object
 16  is_temporarily_closed  0 non-null      float64
 17  closed_on              96 non-null     object
 18  address                95 non-null     object
 19  review_keywords        64 non-null     object
 20  link                   96 non-null     object
 21  query                  96 non-null     object
dtypes: float64(4), int64(1), object(17)
memory usage: 16.6+ KB

In [19]:
df4.head()

,place_id,name,description,is_spending_on_ads,reviews,rating,competitors,website,phone,can_claim,...,images,hours,most_popular_times,popular_times,menu,reservations,order_online_links,featured_reviews,detailed_reviews,query
0,ChIJYQIbq0US2C0RoXbX5gkHWUY,Kahoona Beach,NaN,NaN,22,4.3,[],NaN,0857-3335-9123,NaN,...,"[{""about"":""Semua"",""link"":""https://lh3.googleus...",[],Not Present,Not Present,NaN,[],[],"[{""review_id"":""ChdDSUhNMG9nS0VJQ0FnSUQ2a09DNGd...","[{""review_id"":""Ci9DQUlRQUNvZENodHljRjlvT2paRWV...",beaches in bangkalan
1,ChIJxWCJ0M4C2C0RVkIRQqMGJHs,Pantai Goa Petapa,NaN,NaN,319,4.2,[],NaN,NaN,NaN,...,[],[],"[{""hour_of_day"":15,""average_popularity"":28.428...","{""Monday"":[{""hour_of_day"":6,""time_label"":""06.0...",NaN,[],[],[],"[{""review_id"":""Ci9DQUlRQUNvZENodHljRjlvT214R1N...",beaches in bangkalan
2,ChIJCb-H_gM_2C0RotQ5H2cQ_9g,Pantai Siring Kemuning,NaN,NaN,511,4.0,[],http://www.pulaumadura.com/,NaN,NaN,...,[],[],"[{""hour_of_day"":15,""average_popularity"":28.857...","{""Monday"":[{""hour_of_day"":6,""time_label"":""06.0...",NaN,[],[],[],"[{""review_id"":""Ci9DQUlRQUNvZENodHljRjlvT2t0cFd...",beaches in bangkalan
3,ChIJF_T0zSUD2C0RJFytakQa2VM,Pantai Rindu,NaN,NaN,1386,3.7,"[{""name"":""Dermaga Rindu"",""link"":""https://www.g...",NaN,NaN,1.0,...,"[{""about"":""Semua"",""link"":""https://lh3.googleus...",[],Not Present,Not Present,NaN,[],[],"[{""review_id"":""Ci9DQUlRQUNvZENodHljRjlvT2poalF...","[{""review_id"":""Ci9DQUlRQUNvZENodHljRjlvT25OdWR...",beaches in bangkalan
4,ChIJuRiSbwAd2C0RDp_Iezqhlmk,Merah Putih Beach,NaN,NaN,1,5.0,"[{""name"":""Pantai Gebang"",""link"":""https://www.g...",NaN,NaN,1.0,...,"[{""about"":""Semua"",""link"":""https://lh3.googleus...",[],Not Present,Not Present,NaN,[],[],"[{""review_id"":""ChdDSUhNMG9nS0VJQ0FnSUNiclA3bmx...","[{""review_id"":""ChdDSUhNMG9nS0VJQ0FnSUNiclA3bmx...",beaches in bangkalan

In [ ]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 43 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   place_id               96 non-null     object
 1   name                   96 non-null     object
 2   description            13 non-null     object
 3   is_spending_on_ads     0 non-null      float64
 4   reviews                96 non-null     int64
 5   rating                 96 non-null     float64
 6   competitors            96 non-null     object
 7   website                11 non-null     object
 8   phone                  18 non-null     object
 9   can_claim              52 non-null     float64
 10  owner                  96 non-null     object
 11  featured_image         92 non-null     object
 12  main_category          96 non-null     object
 13  categories             96 non-null     object
 14  workday_timing         45 non-null     object
 15  is_temporarily_closed  0 non-null      float64
 16  is_permanently_closed  0 non-null      float64
 17  closed_on              96 non-null     object
 18  address                95 non-null     object
 19  review_keywords        96 non-null     object
 20  link                   96 non-null     object
 21  status                 45 non-null     object
 22  price_range            2 non-null      object
 23  reviews_per_rating     96 non-null     object
 24  featured_question      0 non-null      float64
 25  reviews_link           96 non-null     object
 26  coordinates            96 non-null     object
 27  plus_code              19 non-null     object
 28  detailed_address       96 non-null     object
 29  time_zone              94 non-null     object
 30  cid                    96 non-null     uint64
 31  data_id                96 non-null     object
 32  about                  96 non-null     object
 33  images                 96 non-null     object
 34  hours                  96 non-null     object
 35  most_popular_times     96 non-null     object
 36  popular_times          96 non-null     object
 37  menu                   0 non-null      float64
 38  reservations           96 non-null     object
 39  order_online_links     96 non-null     object
 40  featured_reviews       96 non-null     object
 41  detailed_reviews       96 non-null     object
 42  query                  96 non-null     object
dtypes: float64(7), int64(1), object(34), uint64(1)
memory usage: 32.4+ KB

: